M48
; DRILL file {KiCad (6.0.11)} date Mon Mar 18 15:41:39 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-18T15:41:39-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1378
%
G90
G05
T1
X6.5Y-3.48
X6.5Y-3.57
T2
X6.79Y-3.34
X6.79Y-3.44
X6.89Y-3.34
X6.89Y-3.44
X6.99Y-3.34
X6.99Y-3.44
X7.09Y-3.34
X7.09Y-3.44
X7.19Y-3.34
X7.19Y-3.44
T3
X8.07Y-3.5053
X8.22Y-3.5053
T4
X5.31Y-3.49
X7.75Y-3.49
T0
M30
